config/routes.rb
Kebapage::Engine.routes.draw do
  resources :media, only: [:index, :create, :destroy]
  resources :static_pages, except: [:show]
  root 'static_pages#index'
end

app/models/kebapage/medium.rb
module Kebapage
  class Medium < ActiveRecord::Base
    has_attached_file :attachment,
                      :styles => Rails.configuration.kebapage.attachment_styles,
                      :url => Rails.configuration.kebapage.attachment_url,
                      :path => Rails.configuration.kebapage.attachment_path

    validates_attachment_size :attachment, :less_than => Rails.configuration.kebapage.attachment_max_size
    validates_attachment_content_type :attachment, :content_type => Rails.configuration.kebapage.attachment_content_type

    Paperclip.interpolates :uniq_file_name do |attachment, style|
      attachment.instance.uniq_file_name
    end

    def uniq_file_name
      Digest::SHA1.hexdigest(id.to_s)
    end
  end
end

app/models/kebapage/static_page.rb
module Kebapage
  class StaticPage < ActiveRecord::Base
    validates :title, :content, presence: true

    def to_param
      "#{id} #{title}".parameterize
    end
  end
end

app/controllers/kebapage/application_controller.rb
module Kebapage
  class ApplicationController < ActionController::Base
    before_filter :authenticate_admin!
    layout Rails.configuration.kebapage.admin_layout
  end
end

app/controllers/kebapage/media_controller.rb
require_dependency 'kebapage/application_controller'

module Kebapage
  class MediaController < ApplicationController
    def index
      @media = Medium.order('attachment_updated_at DESC')
      @medium = Medium.new
    end

    def create
      @medium = Medium.create(attachment: params[:attachment ])
      render json: @medium
    end

    def destroy
      @medium = Medium.find(params[:id])
      @medium.destroy

      if request.xhr?
        render nothing: true
      else
        redirect_to media_path
      end
    end
  end
end

app/controllers/kebapage/static_pages_controller.rb
require_dependency 'kebapage/application_controller'

module Kebapage
  class StaticPagesController < ApplicationController
    before_action :set_static_page, only: [:show, :edit, :update, :destroy]
    skip_before_filter :authenticate_admin!, only: [:show]

    def index
      @static_pages = StaticPage.order('updated_at DESC')
    end

    def show
      render layout: Rails.configuration.kebapage.front_layout, template: 'kebapage/show'
    end

    def new
      @static_page = StaticPage.new
      @medium = Medium.new
    end

    def edit
      @medium = Medium.new
    end

    def create
      @static_page = StaticPage.new(static_page_params)

      if @static_page.save
        redirect_to root_url
      else
        render action: 'new'
      end
    end

    def update
      if @static_page.update(static_page_params)
        redirect_to root_url
      else
        render action: 'edit'
      end
    end

    def destroy
      @static_page.destroy
      redirect_to static_pages_url
    end

    private
      def set_static_page
        @static_page = StaticPage.find(params[:id])
      end

      def static_page_params
        params.require(:static_page).permit(:title, :content)
      end
  end
end

app/helpers/kebapage/application_helper.rb
module Kebapage
  module ApplicationHelper
  end
end

app/helpers/kebapage/media_helper.rb
module Kebapage
  module MediaHelper
  end
end

app/helpers/kebapage/static_pages_helper.rb
module Kebapage
  module StaticPagesHelper
  end
end

app/views/kebapage/media/index.html.haml
- content_for :head do
  = stylesheet_link_tag 'kebapage/application', media: 'all', 'data-turbolinks-track' => true

- content_for :foot do
  = javascript_include_tag 'kebapage/application', 'data-turbolinks-track' => true

.form-group
  = simple_form_for @medium, multipart: true, html: { class: :dropzone, id: 'media-dropzone' } do |f|
    = f.input :attachment, as: :hidden

.panel.panel-default.grid
  .panel-heading
    %i.icon-table.icon-large
    #{I18n.t('kebapage.media_manager')}

  %table.table
    %thead
      %tr
        %th #
        %th #{I18n.t('kebapage.file_name')}
        %th #{I18n.t('kebapage.file_type')}
        %th #{I18n.t('kebapage.file_size')}
        %th #{I18n.t('kebapage.upload_date')}
        %th.actions
          #{I18n.t('kebapage.action')}

    %t.body.success
      - @media.each do |media|
        %tr
          %td
            = (@media.index media) + 1
          %td
            = media.attachment_file_name
          %td
            = media.attachment_content_type
          %td
            = "#{(media.attachment_file_size.to_i / 1024)} KB"
          %td
            = media.attachment_updated_at.to_date
          %td.action
            %a.btn.btn-success{href: media.attachment.url, target: '_blank' }
              %i.icon-eye-open
            = link_to medium_path(media), method: :delete, data: { confirm: I18n.t('kebapage.ru_sure') }, class: 'btn btn-danger' do
              %i.icon-trash

app/views/kebapage/static_pages/_form.html.haml
- content_for :head do
  = stylesheet_link_tag 'kebapage/application', media: 'all', 'data-turbolinks-track' => true

- content_for :foot do
  = javascript_include_tag 'kebapage/application', 'data-turbolinks-track' => true

.panel.panel-default
  .panel-heading
    %i.icon-edit.icon-large
    Form
  .panel-body

    =simple_form_for @static_page do |f|
      .form-group
        = f.input :title, label: I18n.t('kebapage.title'), placeholder: I18n.t('kebapage.title_placeholder')

      .form-group
        = f.input :content, input_html: {class: 'wysihtml5', rows: 15}, label: I18n.t('kebapage.content'), placeholder: I18n.t('kebapage.content_placeholder')

      .form-actions
        %button.btn.btn-default{type: 'submit'} #{I18n.t('kebapage.submit')}
        %a.btn{href: static_pages_path} #{I18n.t('kebapage.cancel')}

app/views/kebapage/static_pages/edit.html.haml
%h1 #{I18n.t('kebapage.edit_page')}

= render 'form', :static_page => @static_page

app/views/kebapage/static_pages/index.html.haml
.panel.panel-default.grid
  .panel-heading
    %i.icon-table.icon-large
    #{I18n.t('kebapage.static_pages')}

  %table.table
    %thead
      %tr
        %th #
        %th #{I18n.t('kebapage.title')}
        %th #{I18n.t('kebapage.date')}
        %th.actions
          #{I18n.t('kebapage.action')}
    %tbody.success
      - @static_pages.each do |static_page|
        %tr
          %td
            = (@static_pages.index static_page) + 1
          %td
            = static_page.title
          %td
            = static_page.updated_at.to_date
          %td.action
            %a.btn.btn-success{href: main_app.pages_path(static_page), data: { toggle: 'tooltip'}, title: I18n.t('kebapage.show')}
              %i.icon-zoom-in
            %a.btn.btn-info{href: edit_static_page_path(static_page)}
              %i.icon-edit
            = link_to static_page_path(static_page), method: :delete, data: { confirm: I18n.t('kebapage.ru_sure')}, class: 'btn btn-danger' do
              %i.icon-trash

= link_to I18n.t('kebapage.new_page'), new_static_page_path, method: :get, class: 'btn btn-default btn-success'

app/views/kebapage/static_pages/new.html.haml
%h1 #{I18n.t('kebapage.new_page')}

= render 'form', :static_page => @static_page

app/views/kebapage/static_pages/show.html.haml
%p
  = @static_page.content.html_safe

app/views/layouts/kebapage/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kebapage</title>
  <%= stylesheet_link_tag    "kebapage/application", media: "all" %>
  <%= javascript_include_tag "kebapage/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>